/**
 * Unified CRM schema definitions.
 *
 * A Contact can appear in multiple sources. The unified record links them all.
 * An Interaction is any message/conversation event from any source.
 */

/**
 * Create a blank unified contact record.
 * @param {string} id  - stable unique id (generated by merge.js)
 */
function createContact(id) {
    return {
        id,                // e.g. "c_001"
        name: null,        // best known display name
        phones: [],        // ["+447..."]
        emails: [],        // ["foo@example.com"]
        notes: null,       // freeform notes
        tags: [],          // ["investor", "friend"]
        sources: {
            whatsapp: null,        // { id, number, isMyContact, isBusiness, about, profilePic }
            linkedin: null,        // { name, email, company, position, connectedOn, profileUrl }
            telegram: null,        // { userId, name, phone }
            email: null,           // { email, name, firstSeen }
            googleContacts: null,  // { name, phones, emails, org, title, note, birthday }
            sms: null,             // { phone, contactName, messageCount, lastMessageAt }
        },
        lastContactedAt: null,   // ISO timestamp of most recent interaction
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    };
}

/**
 * Create a unified interaction record from a raw message.
 * @param {string} source  - "whatsapp" | "linkedin" | "telegram" | "email"
 * @param {object} raw     - source-specific message object
 */
function createInteraction(source, raw) {
    return {
        id: raw.id || null,
        source,
        timestamp: raw.timestamp || raw.date || null,
        from: raw.from || null,
        to: raw.to || null,
        body: raw.body || raw.text || raw.content || null,
        subject: raw.subject || null,         // email / LinkedIn InMail
        chatId: raw.chatId || raw.conversationId || null,
        chatName: raw.chatName || null,
        type: raw.type || 'message',
        raw,                                  // keep original for reference
    };
}

module.exports = { createContact, createInteraction };
